detecturl: "http://10.250.164.198:5000//detect"
#detecturl: "http://127.0.0.1:5000//detect"
accounts:
  -
    machineid: "demo"
    password: "123456"
goods:
  - "BSS"
  - "FANTA"
  - "JDB"
  - "KSFBHC"
  - "VTMSSL"
  - "MD"
  - "MZYGLC"
  - "TYNL"
  - "TYASM"
  - "YYKX"
  - "VITANM"
  - "YLHSNN"
  - "KSFXL"
  - "KSFSMT"
  - "KSFT"
  - "KSFLC"
  - "KSFFY"
  - "KSFMM"
  - "KSFJN"
  - "XMTTLL"
  - "XMLLQN"
  - "YLJH"
  - "MZYRG"
  - "MZYSH"
  - "BYLMZ"
  - "BYBXG"
  - "COCACOLA"
  - "SPIRITNM"
  - "YQSLBS"
  - "YQSLRT"
  - "YQSLRC"
  - "MNDPT"
  - "MNDXG"
  - "NSPEPSI"
  - "JTPEPSI"
  - "DPCP"
  - "HKGN"
  - "KSFWH"
  - "YYMM"
  - "YYLP"
  - "YYHM"
  - "VTMSRS"
  - "CPMW"
  - "BGZMHT"
  - "YYDTGY"
  - "BJKZW"
  - "WHHGWS"
  - "JDLLM"
  - "JDLNM"
  - "DSHC"
  - "BSKL"
  - "COCAXW"
  - "SPIRITXW"
  - "YQYWSD"
  - "YQNMSD"
  - "QCQNSD"
  - "QCMTSD"
  - "NFSQNH"
  - "NFSQYL"
  - "DPWSS"
  - "COCACOF"
  - "KSJCM"
  - "KSJCN"
  - "JJBT"
  - "JJQM"
  - "WTMNM"
  - "KSFCCNM"
  - "COCAYGNM"
  - "CPXM"
  - "COCACH"
  - "COCACL"
  - "COCACP"
  - "QCCCNH"
  - "QCCCTW"
  - "DFSYWL"
  - "NFGYT"
  - "NFGYP"
  - "MZYQO"
  - "MZYZT"
  - "MZYBN"
  - "TYYGXC"
  - "BQYCFS"
  - "YQSLNL"
  - "YQSLYW"
  - "YBDJYS"
  - "YBDJNM"
  - "GYLM"
  - "WTMWX"
  - "YBZCH"
  - "YBZCW"
  - "XWTWQ"
  - "YXCHYQN"
  - "DDNM"
  - "DJKXDW"
  - "YSMTBW"
  - "LLMLH"
  - "DDSL"
  - "QLSL"
  - "DYDPC"
  - "QLHKMB"
