#detecturl: "http://192.168.1.103:5000//detect"
detecturl: "http://127.0.0.1:5000//detect"
tokenlength: 30
accounts:
  -
    machineid: "demo"
    password: "123456"
goods:
  - "fenda"
  - "yingyangkuaixian"
  - "jiaduobao"
  - "maidong"
  - "TYCL"
  - "BSS"
  - "TYYC"
  - "LLDS"
  - "KSFH"
  - "MZY"
